params:
  epochs:30
  batch_size:32
  np_classes:10
  input_shape:[28,28]
  logs_functions:sparse_categorical_crossentropy
  metrics:accuracy
  optimizer:SGD
  validation_datasize:5000
  

artifacts:
  artifacts_dir:artifact
  model_dr:model
  plot_dr :plots
  checkpoints_dr:checkpoints

logs:
  logs_dir :log_dir
  general_logs:general_logs
  tensorboard_logs:tensorboard_logs